# Generated by Django 5.2.6 on 2025-09-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('puntos', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
